# TCL File Generated by Component Editor 23.1
# Tue May 21 19:16:54 CDT 2024
# DO NOT MODIFY


# 
# user_algorithm "user_algorithm" v1.0
# Francisco Perez 2024.05.21.19:16:54
# Convert RGB to Grayscale
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module user_algorithm
# 
set_module_property DESCRIPTION "Convert RGB to Grayscale"
set_module_property NAME user_algorithm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Video IP Template"
set_module_property AUTHOR "Francisco Perez"
set_module_property DISPLAY_NAME user_algorithm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL user_algorithm_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file alt_vip_common_control_packet_decoder.v VERILOG PATH alt_vip_common_control_packet_decoder.v
add_fileset_file alt_vip_common_control_packet_encoder.v VERILOG PATH alt_vip_common_control_packet_encoder.v
add_fileset_file alt_vip_common_flow_control_wrapper.v VERILOG PATH alt_vip_common_flow_control_wrapper.v
add_fileset_file alt_vip_common_stream_input.v VERILOG PATH alt_vip_common_stream_input.v
add_fileset_file alt_vip_common_stream_output.v VERILOG PATH alt_vip_common_stream_output.v
add_fileset_file user_algorithm_core.v VERILOG PATH user_algorithm_core.v
add_fileset_file user_algorithm_top.v VERILOG PATH user_algorithm_top.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter BITS_PER_SYMBOL INTEGER 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE INTEGER
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter SYMBOLS_PER_BEAT INTEGER 3
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 3
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE INTEGER
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point din
# 
add_interface din avalon_streaming end
set_interface_property din associatedClock clock
set_interface_property din associatedReset reset
set_interface_property din dataBitsPerSymbol 8
set_interface_property din errorDescriptor ""
set_interface_property din firstSymbolInHighOrderBits true
set_interface_property din maxChannel 0
set_interface_property din readyLatency 1
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din din_data data Input "(((BITS_PER_SYMBOL*SYMBOLS_PER_BEAT)-1)) - (0) + 1"
add_interface_port din din_eop endofpacket Input 1
add_interface_port din din_ready ready Output 1
add_interface_port din din_sop startofpacket Input 1
add_interface_port din din_valid valid Input 1


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 1
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout dout_data data Output "(((BITS_PER_SYMBOL*SYMBOLS_PER_BEAT)-1)) - (0) + 1"
add_interface_port dout dout_eop endofpacket Output 1
add_interface_port dout dout_ready ready Input 1
add_interface_port dout dout_sop startofpacket Output 1
add_interface_port dout dout_valid valid Output 1

